package org.pql.test;

import java.sql.SQLException;
import java.util.Iterator;
import java.util.List;

import org.themis.ir.Document;
import org.themis.ir.vsm.VSM;
import org.themis.util.LETTERCASE;
import org.themis.util.PREPROCESS;
import org.themis.util.STEMMER;

public class VSMTest
{
        public static void main(String[] args) throws SQLException, ClassNotFoundException
        {
        		VSM vsm = new VSM("localhost","themis/","postgres","password");
                
                vsm.clear();
                
                vsm.setParameter(PREPROCESS.LETTERCASE.toString(), LETTERCASE.UPPER.toString());
                vsm.setParameter(PREPROCESS.STEMMER.toString(), STEMMER.PORTER.toString());
                
                vsm.addStopword("a");
                vsm.addStopword("the");
                
                vsm.addDocument("URL	1", "claim for support exists", false);
                vsm.addDocument("URL	2", "asset shutdown posted", false);
                vsm.addDocument("URL	3", "depreciation should be posted regularly", false);
                vsm.addDocument("URL	4", "fixed asset was bought w/o purchase order", false);
                vsm.addDocument("URL	5", "assign asset to building  if required", false);
                vsm.addDocument("URL	6", "new master record is necessary", false);
                vsm.addDocument("URL	7", "leased asset was bought", false);
                vsm.addDocument("URL	8", "post capitalization to be posted", false);
                vsm.addDocument("URL	9", "acquisitions to be entered", false);
                vsm.addDocument("URL	10", "assign asset to property  if required", false);
                vsm.addDocument("URL	11", "fixed asset was found", false);
                vsm.addDocument("URL	12", "fixed asset was given", false);
                vsm.addDocument("URL	13", "fixed asset is changed", false);
                vsm.addDocument("URL	14", "group asset to be created", false);
                vsm.addDocument("URL	15", "an asset master record should be changed", false);
                vsm.addDocument("URL	16", "asset master record is incomplete", false);
                vsm.addDocument("URL	17", "retirements to be entered", false);
                vsm.addDocument("URL	18", "fixed asset created", false);
                vsm.addDocument("URL	19", "revaluation should be carr out f first time", false);
                vsm.addDocument("URL	20", "revaluation is necessary due to post capi  talization", false);
                vsm.addDocument("URL	21", "asset master record does not exist", false);
                vsm.addDocument("URL	22", "assets to be shut down", false);
                vsm.addDocument("URL	23", "retirement for lva to be carried out", false);
                vsm.addDocument("URL	24", "retirement was posted and checked", false);
                vsm.addDocument("URL	25", "retirement within group to be posted", false);
                vsm.addDocument("URL	26", "acquisition within group posted", false);
                vsm.addDocument("URL	27", "asset transfer within a client exists", false);
                vsm.addDocument("URL	28", "retirement from group posted", false);
                vsm.addDocument("URL	29", "operating lease procedure should be used", false);
                vsm.addDocument("URL	30", "acquisition within group to be posted", false);
                vsm.addDocument("URL	31", "valuation leased asset is determined", false);
                vsm.addDocument("URL	32", "index series was updated", false);
                vsm.addDocument("URL	33", "insurance contract was closed", false);
                vsm.addDocument("URL	34", "revaluation is used repeatedly", false);
                vsm.addDocument("URL	35", "index series must be updated", false);
                vsm.addDocument("URL	36", "revaluation was made", false);
                vsm.addDocument("URL	37", "fixed asset should be insured", false);
                vsm.addDocument("URL	38", "fixed asset should be split", false);
                vsm.addDocument("URL	39", "fixed asset was rebuilt", false);
                vsm.addDocument("URL	40", "class assignment needs changing", false);
                vsm.addDocument("URL	41", "busarea/ cost center assignment needs to be changed", false);
                vsm.addDocument("URL	42", "asset under construction should be settled", false);
                vsm.addDocument("URL	43", "stock mat should be posted to fix asset", false);
                vsm.addDocument("URL	44", "subsequent valuation change is necessary", false);
                vsm.addDocument("URL	45", "transactions completed", false);
                vsm.addDocument("URL	46", "costs were settled by cost element to asset under construction", false);
                vsm.addDocument("URL	47", "features of depreciation area must be changed", false);
                vsm.addDocument("URL	48", "unplanned depreciation should be used", false);
                vsm.addDocument("URL	49", "unit of production method of depreciation has been prepared", false);
                vsm.addDocument("URL	50", "unit of production depreciation is to be posted", false);
                vsm.addDocument("URL	51", "new valuation key is necessary", false);
                vsm.addDocument("URL	52", "costs were settled with secondary cost elements to asset under construction", false);
                vsm.addDocument("URL	53", "special tax depreciation is only to be partly claimed", false);
                vsm.addDocument("URL	54", "useful life should be changed", false);
                vsm.addDocument("URL	55", "shortened fiscal year is necessary", false);
                vsm.addDocument("URL	56", "employment fluctuations are to be included when calculating depreciation", false);
                vsm.addDocument("URL	57", "recalcula  tion of de  preciation was carried out", false);
                vsm.addDocument("URL	58", "service order is settled to asset", false);
                vsm.addDocument("URL	59", "order settled on plant", false);
                vsm.addDocument("URL	60", "payments must be released", false);
                vsm.addDocument("URL	61", "payment must be effected", false);
                vsm.addDocument("URL	62", "vendor down payment is to be cleared", false);
                vsm.addDocument("URL	63", "new value method is not necessary", false);
                vsm.addDocument("URL	64", "inv profile specified w/summary settlement", false);
                vsm.addDocument("URL	65", "investment profile with line item settlement is specified", false);
                vsm.addDocument("URL	66", "posting was allowed despite budget overrun", false);
                vsm.addDocument("URL	67", "program positions released", false);
                vsm.addDocument("URL	68", "budget is to be updated", false);
                vsm.addDocument("URL	69", "posting was rejected due to budget overrun", false);
                vsm.addDocument("URL	70", "assigned funds are within tolerance limits", false);
                vsm.addDocument("URL	71", "measure settled partially", false);
                vsm.addDocument("URL	72", "measure is settled completely", false);
                vsm.addDocument("URL	73", "multiple appropriation requests are to be changed", false);
                vsm.addDocument("URL	74", "mass changes were made", false);
                vsm.addDocument("URL	75", "investment plan is to be revised", false);
                vsm.addDocument("URL	76", "appropri  ation request is to be processed", false);
                vsm.addDocument("URL	77", "internal order is to be created", false);
                vsm.addDocument("URL	78", "19", false);
                vsm.addDocument("URL	79", "variant is processed", false);
                vsm.addDocument("URL	80", "14", false);
                vsm.addDocument("URL	81", "program definition is to be changed", false);
                vsm.addDocument("URL	82", "program structure is to be determined", false);
                vsm.addDocument("URL	83", "program structure is processed", false);
                vsm.addDocument("URL	84", "program is to be created for new fiscal year", false);
                vsm.addDocument("URL	85", "new plan version is to be created", false);
                vsm.addDocument("URL	86", "order is assigned to an investment program", false);
                vsm.addDocument("URL	87", "supplement requests exist for current measures", false);
                vsm.addDocument("URL	88", "overhead debited to capital investment order", false);
                vsm.addDocument("URL	89", "plan is approved on last approval level", false);
                vsm.addDocument("URL	90", "overall costs for project are determined", false);
                vsm.addDocument("URL	91", "loss of a leased system has occurred", false);
                vsm.addDocument("URL	92", "leased system must be scrapped", false);
                vsm.addDocument("URL	93", "premature termination of lease agreement necessary", false);
                vsm.addDocument("URL	94", "leasing agreement runs out", false);
                vsm.addDocument("URL	95", "periodic lease payment is necessary", false);
                vsm.addDocument("URL	96", "leased asset should be bought", false);
                vsm.addDocument("URL	97", "organizational allocations must be changed", false);
                vsm.addDocument("URL	98", "leasing agrmnt conditions were changed", false);
                vsm.addDocument("URL	99", "new sub  number was determined", false);
                vsm.addDocument("URL	100", "goods receipt of leased asset carriout", false);
                vsm.addDocument("URL	101", "asset class was determined", false);
                vsm.addDocument("URL	102", "new capital lease para  meters were determined", false);
                vsm.addDocument("URL	103", "requisition released for scheduling agreement schedule/sa release", false);
                vsm.addDocument("URL	104", "purchase requisition released for contract release order", false);
                vsm.addDocument("URL	105", "purchase requisition released for purchase order", false);
                vsm.addDocument("URL	106", "to item confirmed without differences", false);
                vsm.addDocument("URL	107", "transfer order item with difference exists", false);
                vsm.addDocument("URL	108", "transfer order item is confirmed", false);
                vsm.addDocument("URL	109", "inward material movement to be posted", false);
                vsm.addDocument("URL	110", "goods receipt posted", false);
                vsm.addDocument("URL	111", "purchase order transmitted", false);
                vsm.addDocument("URL	112", "purchase order created", false);
                vsm.addDocument("URL	113", "material has been picked", false);
                vsm.addDocument("URL	114", "shipping unit is created", false);
                vsm.addDocument("URL	115", "shipping unit is to be created", false);
                vsm.addDocument("URL	116", "quotation chosen", false);
                vsm.addDocument("URL	117", "quotation rejected", false);
                vsm.addDocument("URL	118", "requisition flagged for issue of rfq", false);
                vsm.addDocument("URL	119", "source of supply assigned", false);
                vsm.addDocument("URL	120", "invoice parked", false);
                vsm.addDocument("URL	121", "invoice posted", false);
                vsm.addDocument("URL	122", "other goods receipt exists", false);
                vsm.addDocument("URL	123", "idoc received", false);
                vsm.addDocument("URL	124", "delivery urged", false);
                vsm.addDocument("URL	125", "reminder sent", false);
                vsm.addDocument("URL	126", "idoc processing initiated for shipping notification", false);
                vsm.addDocument("URL	127", "components to be replenished as per delivery", false);
                vsm.addDocument("URL	128", "components are to be replenished per goods issue", false);
                vsm.addDocument("URL	129", "material withdrawal is to be posted", false);
                vsm.addDocument("URL	130", "system inventory record is created", false);
                vsm.addDocument("URL	131", "continuous inventory wm is to be performed", false);
                vsm.addDocument("URL	132", "no variance was determined", false);
                vsm.addDocument("URL	133", "recount is necessary", false);
                vsm.addDocument("URL	134", "recount is not necessary", false);
                vsm.addDocument("URL	135", "recount is initiated", false);
                vsm.addDocument("URL	136", "cycle counting is to be performed", false);
                vsm.addDocument("URL	137", "product safety data is to be processed", false);
                vsm.addDocument("URL	138", "processing is completed", false);
                vsm.addDocument("URL	139", "drilldown reporting is to be carried out", false);
                vsm.addDocument("URL	140", "result is displayed", false);
                vsm.addDocument("URL	141", "shipping printing of reports is to be triggered", false);
                vsm.addDocument("URL	142", "attributes are to be formulated in text form", false);
                vsm.addDocument("URL	143", "create standard operating procedure", false);
                vsm.addDocument("URL	144", "agents in the enterprise are to be entered", false);
                vsm.addDocument("URL	145", "accident data is to be entered", false);
                vsm.addDocument("URL	146", "dangerous goods master is to be processed", false);
                vsm.addDocument("URL	147", "basic data is to be processed", false);
                vsm.addDocument("URL	148", "automatic retrieval of dangerous goods data is to be carried out", false);
                vsm.addDocument("URL	149", "plan proposal for sales planning to be created", false);
                vsm.addDocument("URL	150", "plan needs to be changed", false);
                vsm.addDocument("URL	151", "profit center planning is prepared", false);
                vsm.addDocument("URL	152", "profit center planning to be prepared excel upload", false);
                vsm.addDocument("URL	153", "profit center planning to be prepared new definition", false);
                vsm.addDocument("URL	154", "profit center planning is to be prepared copy plan", false);
                vsm.addDocument("URL	155", "profit center planning to be prepared copy actual", false);
                vsm.addDocument("URL	156", "cost estimate needs to be revised due to variances", false);
                vsm.addDocument("URL	157", "costing for co products is prepared", false);
                vsm.addDocument("URL	158", "costing with quantity structure prepared", false);
                vsm.addDocument("URL	159", "costing without quantity structure prepared", false);
                vsm.addDocument("URL	160", "result complete  costing released", false);
                vsm.addDocument("URL	161", "product costs are allocated", false);
                vsm.addDocument("URL	162", "costs/ revenues were allocated to profitability analysis", false);
                vsm.addDocument("URL	163", "production variances are to be settled", false);
                vsm.addDocument("URL	164", "overhead costs are to be settled to profitability analysis", false);
                vsm.addDocument("URL	165", "allocation of cost center costs required", false);
                vsm.addDocument("URL	166", "project costs/ revenues to be settled to profitability analysis", false);
                vsm.addDocument("URL	167", "orders to be settled to profitability analysis", false);
                vsm.addDocument("URL	168", "allocation of process costs required", false);
                vsm.addDocument("URL	169", "balance sheet items were distributed", false);
                vsm.addDocument("URL	170", "balance sheet items were copied to profit center accounting", false);
                vsm.addDocument("URL	171", "profit center transfer of receivables/ payables required", false);
                vsm.addDocument("URL	172", "profit center transfer of fixed assets required", false);
                vsm.addDocument("URL	173", "profit center transfer of material inventories required", false);
                vsm.addDocument("URL	174", "distribute profit center overhead costs", false);
                vsm.addDocument("URL	175", "profit center transfer of wip required", false);
                vsm.addDocument("URL	176", "product cost analysis required for co products", false);
                vsm.addDocument("URL	177", "product cost analysis required for order related controlling", false);
                vsm.addDocument("URL	178", "control measures taken due to variances", false);
                vsm.addDocument("URL	179", "statistical key figures entered", false);
                vsm.addDocument("URL	180", "statistical key figure is to be transferred from lis", false);
                vsm.addDocument("URL	181", "statistical key figure is to be entered manually", false);
                vsm.addDocument("URL	182", "cost object hierarchy is created", false);
                vsm.addDocument("URL	183", "cost object is processed", false);
                vsm.addDocument("URL	184", "expenditure budget increased", false);
                vsm.addDocument("URL	185", "set invoice to paid", false);
                vsm.addDocument("URL	186", "additional budget structuring is not required", false);
                vsm.addDocument("URL	187", "actual data does not need to be checked", false);
                vsm.addDocument("URL	188", "matching has taken place", false);
                vsm.addDocument("URL	189", "fund edited", false);
                vsm.addDocument("URL	190", "actual data must be checked", false);
                vsm.addDocument("URL	191", "transfer has occurred in the area of financial assets", false);
                vsm.addDocument("URL	192", "intercompany profit/ loss in trans  ferred assets is eliminated", false);
                vsm.addDocument("URL	193", "export file pc is transferred", false);
                vsm.addDocument("URL	194", "file is transferred as pc file", false);
                vsm.addDocument("URL	195", "rollup extract file is transferred", false);
                vsm.addDocument("URL	196", "extract is transferred as unix file", false);
                vsm.addDocument("URL	197", "extract is transferred from r/2", false);
                vsm.addDocument("URL	198", "data is updated realtime", false);
                vsm.addDocument("URL	199", "extract is transferred by idoc", false);
                vsm.addDocument("URL	200", "extract/ download for r/ 2 is created", false);
                vsm.addDocument("URL	201", "changes in current year entered for purchase method company", false);
                vsm.addDocument("URL	202", "rollup is carried out in the same system", false);
                vsm.addDocument("URL	203", "changes for current year are entered for proportionally consolidated co", false);
                vsm.addDocument("URL	204", "materials should be subject to fifo valuation", false);
                vsm.addDocument("URL	205", "fifo valuation to be based on single receipts", false);
                vsm.addDocument("URL	206", "materials are subject to fifo valuation", false);
                vsm.addDocument("URL	207", "document extract for fifo was formed", false);
                vsm.addDocument("URL	208", "fifo begins in the middle of the fiscal year", false);
                vsm.addDocument("URL	209", "account has dunning block", false);
                vsm.addDocument("URL	210", "line items to be cleared", false);
                vsm.addDocument("URL	211", "manual clearing is complete", false);
                vsm.addDocument("URL	212", "customer initiates invoice/ credit memo", false);
                vsm.addDocument("URL	213", "vendor invoice is to be parked", false);
                vsm.addDocument("URL	214", "interest to be calculated on account balances", false);
                vsm.addDocument("URL	215", "interest on arrears to be calculated", false);
                vsm.addDocument("URL	216", "down payment can be cleared automatic", false);
                vsm.addDocument("URL	217", "down payment is to be cleared manually", false);
                vsm.addDocument("URL	218", "bill of exchange payable to be posted", false);
                vsm.addDocument("URL	219", "bill of exchange payable posted", false);
                vsm.addDocument("URL	220", "incoming payments were rejected", false);
                vsm.addDocument("URL	221", "manual outgoing payment to be processed", false);
                vsm.addDocument("URL	222", "automatic outgoing payment to be processed", false);
                vsm.addDocument("URL	223", "payments have not been created", false);
                vsm.addDocument("URL	224", "payment request is created", false);
                vsm.addDocument("URL	225", "direct g/l account posting to be made", false);
                vsm.addDocument("URL	226", "posting to be made in general ledger", false);
                vsm.addDocument("URL	227", "p+l statement account is created", false);
                vsm.addDocument("URL	228", "balance sheet account is created", false);
                vsm.addDocument("URL	229", "long term receivables should be discounted", false);
                vsm.addDocument("URL	230", "manual foreign currency valuation carried out", false);
                vsm.addDocument("URL	231", "doubtful receivables to be devalued due to country del credere", false);
                vsm.addDocument("URL	232", "manual foreign currency valuation to be carried out", false);
                vsm.addDocument("URL	233", "customer specific valuation to be made", false);
                vsm.addDocument("URL	234", "foreign currency valuation carried out", false);
                vsm.addDocument("URL	235", "flat rate individual adjustment is carried out", false);
                vsm.addDocument("URL	236", "g/l accounts due for analysis", false);
                vsm.addDocument("URL	237", "balance analysis carried out", false);
                vsm.addDocument("URL	238", "g/l line item analysis carried out", false);
                vsm.addDocument("URL	239", "retrograde withdrawal to be posted", false);
                vsm.addDocument("URL	240", "material is not available", false);
                vsm.addDocument("URL	241", "equipment is assigned to superior equipment", false);
                vsm.addDocument("URL	242", "equipment is installed  dismantled or modified", false);
                vsm.addDocument("URL	243", "cust mail campaign to be carried out", false);
                vsm.addDocument("URL	244", "customer inquires about products", false);
                vsm.addDocument("URL	245", "service contract to be created w/o ref to quotation", false);
                vsm.addDocument("URL	246", "service contract to be offered", false);
                vsm.addDocument("URL	247", "sales activity is to be processed", false);
                vsm.addDocument("URL	248", "credit/ debit memo is granted", false);
                vsm.addDocument("URL	249", "credit/ debit memo request is rejected", false);
                vsm.addDocument("URL	250", "delivery is to be created", false);
                vsm.addDocument("URL	251", "delivery is relevant for billing", false);
                vsm.addDocument("URL	252", "order generated and delivery opened", false);
                vsm.addDocument("URL	253", "inspection before goods issue is to be carried out", false);
                vsm.addDocument("URL	254", "inspect independent of goods issue", false);
                vsm.addDocument("URL	255", "inventory management posting already carried out", false);
                vsm.addDocument("URL	256", "difference is settled on srce bin location", false);
                vsm.addDocument("URL	257", "difference has been posted to interface", false);
                vsm.addDocument("URL	258", "goods movement is posted", false);
                vsm.addDocument("URL	259", "change to terms of credit refused", false);
                vsm.addDocument("URL	260", "credit limit check is to be performed manually", false);
                vsm.addDocument("URL	261", "terms of credit have changed", false);
                vsm.addDocument("URL	262", "credit limit is not sufficient", false);
                vsm.addDocument("URL	263", "external sales force/ customer complaint is to be created", false);
                vsm.addDocument("URL	264", "evaluation from qmis indicates quality problems", false);
                vsm.addDocument("URL	265", "defect requires manual quality notification", false);
                vsm.addDocument("URL	266", "sales and distribution document must be created for service notification", false);
                vsm.addDocument("URL	267", "document blocked due to insufficent hedge", false);
                vsm.addDocument("URL	268", "enterprise provisions for staff/ change planning are adopted", false);
                vsm.addDocument("URL	269", "need for provisions for staff/ change planning exists", false);
                vsm.addDocument("URL	270", "further implementation actions must be performed", false);
                vsm.addDocument("URL	271", "provisions of staff/ change planning must be corrected", false);
                vsm.addDocument("URL	272", "employee is retired", false);
                vsm.addDocument("URL	273", "employee is in an inactive work relationship", false);
                vsm.addDocument("URL	274", "employee has left", false);
                vsm.addDocument("URL	275", "applicant is put on hold for vacancy", false);
                vsm.addDocument("URL	276", "applicant must be offered contract for vacancy", false);
                vsm.addDocument("URL	277", "applicant is rejected for vacancy", false);
                vsm.addDocument("URL	278", "additional implementation actions are required", false);
                vsm.addDocument("URL	279", "need for personnel development system exists", false);
                vsm.addDocument("URL	280", "personnel development system is adopted", false);
                vsm.addDocument("URL	281", "personnel development system must be corrected", false);
                vsm.addDocument("URL	282", "personnel appraisal system must be corrected", false);
                vsm.addDocument("URL	283", "need for personnel appraisal system exists", false);
                vsm.addDocument("URL	284", "personnel appraisal system is adopted", false);
                vsm.addDocument("URL	285", "personnel appraisal must be corrected", false);
                vsm.addDocument("URL	286", "need for personnel appraisal exists", false);
                vsm.addDocument("URL	287", "benefit dependent remuneration is to be calculated", false);
                vsm.addDocument("URL	288", "agreed remuneration is to be calculated", false);
                vsm.addDocument("URL	289", "characterized remuneration elements exist", false);
                vsm.addDocument("URL	290", "time dependent remuneration is to be calculated", false);
                vsm.addDocument("URL	291", "set up product structure without variants", false);
                vsm.addDocument("URL	292", "product structure for variants to be set up", false);
                vsm.addDocument("URL	293", "set up product strucuture using cad interface", false);
                vsm.addDocument("URL	294", "sales and production quantities to be planned long to medium term", false);
                vsm.addDocument("URL	295", "execute flexible planning", false);
                vsm.addDocument("URL	296", "sop data to be transferred to demand management", false);
                vsm.addDocument("URL	297", "drp run is to be executed for material", false);
                vsm.addDocument("URL	298", "drp run to be executed for plant / distribution center", false);
                vsm.addDocument("URL	299", "stock transport requisition is generated", false);
                vsm.addDocument("URL	300", "production order is created", false);
                vsm.addDocument("URL	301", "replenishment with manual kanban triggered", false);
                vsm.addDocument("URL	302", "run schedule quantity is created", false);
                vsm.addDocument("URL	303", "stock transfer is posted", false);
                vsm.addDocument("URL	304", "delivery schedule/ release transferred", false);
                vsm.addDocument("URL	305", "pi sheet is sent", false);
                vsm.addDocument("URL	306", "process message received from ext system", false);
                vsm.addDocument("URL	307", "process message has been automatically generated", false);
                vsm.addDocument("URL	308", "control recipe is sent", false);
                vsm.addDocument("URL	309", "carry out product development", false);
                vsm.addDocument("URL	310", "carry out project development in the project", false);
                vsm.addDocument("URL	311", "send product data manually", false);
                vsm.addDocument("URL	312", "check product data", false);
                vsm.addDocument("URL	313", "distribute documents", false);
                vsm.addDocument("URL	314", "send product data automatically", false);
                vsm.addDocument("URL	315", "quotation must be created on basis of plan data", false);
                vsm.addDocument("URL	316", "customer project required", false);
                vsm.addDocument("URL	317", "archived data reviewed", false);
                vsm.addDocument("URL	318", "deletion without archiving executed", false);
                vsm.addDocument("URL	319", "deletion with archiving required", false);
                vsm.addDocument("URL	320", "changes should be adopted", false);
                vsm.addDocument("URL	321", "objects processed must be sent for review", false);
                vsm.addDocument("URL	322", "down payment agreed with customer", false);
                vsm.addDocument("URL	323", "partial payment should be made", false);
                vsm.addDocument("URL	324", "planned orders converted into production orders", false);
                vsm.addDocument("URL	325", "planned orders are converted to process orders", false);
                vsm.addDocument("URL	326", "project planning for customer quotation processing required", false);
                vsm.addDocument("URL	327", "internal project approved", false);
                vsm.addDocument("URL	328", "cross project scheduling required", false);
                vsm.addDocument("URL	329", "dates must be planned for wbs elements", false);
                vsm.addDocument("URL	330", "project/ subproject with activities requires scheduling", false);
                vsm.addDocument("URL	331", "date planning is performed", false);
                vsm.addDocument("URL	332", "revenue planned", false);
                vsm.addDocument("URL	333", "manual revenue planning required", false);
                vsm.addDocument("URL	334", "revenue planning using billing plan required", false);
                vsm.addDocument("URL	335", "product idea exists", false);
                vsm.addDocument("URL	336", "customer order exists", false);
                vsm.addDocument("URL	337", "display changes to digital signature", false);
                vsm.addDocument("URL	338", "check changes", false);
                vsm.addDocument("URL	339", "check dates and transactions", false);
                vsm.addDocument("URL	340", "check product data structure", false);
                vsm.addDocument("URL	341", "create project bom", false);
                vsm.addDocument("URL	342", "create order bom", false);
                vsm.addDocument("URL	343", "quality notification is activated from defects", false);
                vsm.addDocument("URL	344", "automatically created quality notification is to be edited", false);
                vsm.addDocument("URL	345", "valuation flows were generated", false);
                vsm.addDocument("URL	346", "payment request was generated", false);
                vsm.addDocument("URL	347", "flows were released for posting", false);
                vsm.addDocument("URL	348", "customer open items were generated", false);
                vsm.addDocument("URL	349", "g/l posting was generated", false);
                vsm.addDocument("URL	350", "netting proposal was accepted", false);
                vsm.addDocument("URL	351", "planned record created", false);
                vsm.addDocument("URL	352", "planned record processing completed", false);
                vsm.addDocument("URL	353", "clearing is posted", false);
                vsm.addDocument("URL	354", "items to be dunned", false);
                vsm.addDocument("URL	355", "lockbox file has arrived", false);
                vsm.addDocument("URL	356", "loan offer to be processed", false);
                vsm.addDocument("URL	357", "loan application to be processed", false);
                vsm.addDocument("URL	358", "loan was fully disbursed", false);
                vsm.addDocument("URL	359", "interested party makes loan application", false);
                vsm.addDocument("URL	360", "loan was partially disbursed", false);
                vsm.addDocument("URL	361", "notice for change to contract exists", false);
                vsm.addDocument("URL	362", "conditions due to expire", false);
                vsm.addDocument("URL	363", "loan contract to be created", false);
                vsm.addDocument("URL	364", "loan application was rejected", false);
                vsm.addDocument("URL	365", "option was exercised with cash settlement", false);
                vsm.addDocument("URL	366", "termination flows generate settlement payments", false);
                vsm.addDocument("URL	367", "option has expired", false);
                vsm.addDocument("URL	368", "option to be exercised", false);
                vsm.addDocument("URL	369", "option not to be exercised", false);
                vsm.addDocument("URL	370", "option was exercised physically", false);
                vsm.addDocument("URL	371", "option to be terminated", false);
                vsm.addDocument("URL	372", "flows from realized gains/ losses were generated", false);
                vsm.addDocument("URL	373", "interest rate adjustment to be carried out manually", false);
                vsm.addDocument("URL	374", "interest rate adjustment was carried out", false);
                vsm.addDocument("URL	375", "interest rate adjustment to be carried out automatically", false);
                vsm.addDocument("URL	376", "accrual/ deferral flows were generated", false);
                vsm.addDocument("URL	377", "currency option is not to be exercised", false);
                vsm.addDocument("URL	378", "currency option was exercised physically", false);
                vsm.addDocument("URL	379", "currency option was exercised with cash settlement", false);
                vsm.addDocument("URL	380", "currency option is to be terminated", false);
                vsm.addDocument("URL	381", "currency option is to be exercised", false);
                vsm.addDocument("URL	382", "currency option has expired", false);
                vsm.addDocument("URL	383", "flows from cash flow update were generated", false);
                vsm.addDocument("URL	384", "plan allocation of cost center costs required", false);
                vsm.addDocument("URL	385", "settle project", false);
                vsm.addDocument("URL	386", "overhead cost orders to be settled", false);
                vsm.addDocument("URL	387", "plan allocation of process costs required", false);
                vsm.addDocument("URL	388", "project costs are allocated", false);
                vsm.addDocument("URL	389", "cost center costs are allocated", false);
                vsm.addDocument("URL	390", "sales plan is consistent and can be valuated", false);
                vsm.addDocument("URL	391", "overhead cost orders are allocated", false);
                vsm.addDocument("URL	392", "process costs are allocated", false);
                vsm.addDocument("URL	393", "data transfer specified", false);
                vsm.addDocument("URL	394", "task functions for information system set up", false);
                vsm.addDocument("URL	395", "task functions for tools set up", false);
                vsm.addDocument("URL	396", "information system", false);
                vsm.addDocument("URL	397", "tools set up", false);
                vsm.addDocument("URL	398", "integrated reported financial data is to be transferred", false);
                vsm.addDocument("URL	399", "nonintegrated financial reporting data transferred", false);
                vsm.addDocument("URL	400", "nonintegrated reported financial data is to be transferred", false);
                vsm.addDocument("URL	401", "integrated reported financial data", false);
                vsm.addDocument("URL	402", "business planning carried out", false);
                vsm.addDocument("URL	403", "subsequent document is to be created from sales activity", false);
                vsm.addDocument("URL	404", "inquiry items are rejected", false);
                vsm.addDocument("URL	405", "quotation to be created from inquiry", false);
                vsm.addDocument("URL	406", "compression to be carried out according to indicator", false);
                vsm.addDocument("URL	407", "compression according to trading goods is to be carried out", false);
                vsm.addDocument("URL	408", "individual determination is to be carried out", false);
                vsm.addDocument("URL	409", "collective determination is to carried out", false);
                vsm.addDocument("URL	410", "complaints with goods returns is received", false);
                vsm.addDocument("URL	411", "returns to be collected", false);
                vsm.addDocument("URL	412", "customer wants subsequent delivery free of charge", false);
                vsm.addDocument("URL	413", "credit memo is rejected", false);
                vsm.addDocument("URL	414", "credit memo can be created", false);
                vsm.addDocument("URL	415", "returns already dispatched", false);
                vsm.addDocument("URL	416", "subsequent debit reason occurred", false);
                vsm.addDocument("URL	417", "complaint received without goods return", false);
                vsm.addDocument("URL	418", "material placed in storage", false);
                vsm.addDocument("URL	419", "stock placement should be carried out via wcu", false);
                vsm.addDocument("URL	420", "difference must be adjusted in inventory management", false);
                vsm.addDocument("URL	421", "physical inventory is to be carried out", false);
                vsm.addDocument("URL	422", "transfer order created manually", false);
                vsm.addDocument("URL	423", "transfer order created automatically", false);
                vsm.addDocument("URL	424", "document blocked due to legal control", false);
                vsm.addDocument("URL	425", "items are cancelled", false);
                vsm.addDocument("URL	426", "document blocked due to insufficient payment guarantee", false);
                vsm.addDocument("URL	427", "material is removed from stock", false);
                vsm.addDocument("URL	428", "stock removal to be carried out via wcu", false);
                vsm.addDocument("URL	429", "material is issued", false);
                vsm.addDocument("URL	430", "missing parts situation is eliminated", false);
                vsm.addDocument("URL	431", "missing parts situation could not be eliminated", false);
                vsm.addDocument("URL	432", "order related invoice to be created", false);
                vsm.addDocument("URL	433", "delivery without reference is to be created", false);
                vsm.addDocument("URL	434", "requirement for compensation planning preparation", false);
                vsm.addDocument("URL	435", "requirement for correction of specifications of compensation planning", false);
                vsm.addDocument("URL	436", "compensation plan is approved", false);
                vsm.addDocument("URL	437", "need to correct compensation plan exists", false);
                vsm.addDocument("URL	438", "compensation plan exists for approval", false);
                vsm.addDocument("URL	439", "need for compensation planning exists and cannot be delegated further", false);
                vsm.addDocument("URL	440", "need to correct compensation planning exists and cannot be delegated further", false);
                vsm.addDocument("URL	441", "need to correct specifications for budget planning", false);
                vsm.addDocument("URL	442", "need to prepare budget planning exists", false);
                vsm.addDocument("URL	443", "need for long term incentives program", false);
                vsm.addDocument("URL	444", "need for correction of long term incentives program", false);
                vsm.addDocument("URL	445", "no need to act regarding long term incentives program", false);
                vsm.addDocument("URL	446", "long term incentives program is deactivated", false);
                vsm.addDocument("URL	447", "sales order is rejected", false);
                vsm.addDocument("URL	448", "sales order is approved", false);
                vsm.addDocument("URL	449", "check for sales order for long term incentives", false);
                vsm.addDocument("URL	450", "employee notified of rejection of sales order", false);
                vsm.addDocument("URL	451", "registration order is rejected", false);
                vsm.addDocument("URL	452", "business event resource reservation is cancelled", false);
                vsm.addDocument("URL	453", "need for business event resource planning exists", false);
                vsm.addDocument("URL	454", "resource reservation plan must be corrected", false);
                vsm.addDocument("URL	455", "business event resource is reserved", false);
                vsm.addDocument("URL	456", "materials are selected for purchase", false);
                vsm.addDocument("URL	457", "a return is to be entered", false);
                vsm.addDocument("URL	458", "pos sales audit", false);
                vsm.addDocument("URL	459", "a sale is to be entered", false);
                vsm.addDocument("URL	460", "accounts are posted", false);
                vsm.addDocument("URL	461", "need for compensation planning exists", false);
                vsm.addDocument("URL	462", "compensation plan consolidation", false);
                vsm.addDocument("URL	463", "delegation of requirement for compensation planning", false);
                vsm.addDocument("URL	464", "creation/ correction of compensation plan", false);
                vsm.addDocument("URL	465", "compensation plan exists for consolidation", false);
                vsm.addDocument("URL	466", "approval of compensation plan", false);
                vsm.addDocument("URL	467", "compensation planning specifications approved", false);
                vsm.addDocument("URL	468", "delegation of correction requirement for compensation plan", false);
                
                
                long start = System.nanoTime();
                List<Document> res = vsm.searchFull("delegation of requirement for planning", 0, 10);
                long stop = System.nanoTime();
                
                System.out.println(stop-start);
                Iterator<Document> i = res.iterator();
                
                while (i.hasNext())
                {
                        Document doc = i.next();
                        System.out.println(String.format("%1s \t | \t %1.4f \t | \t %3s", doc.getId(), doc.getSimilarity(), doc.getContent()));
                }
        }
}
